In [2]:
import os

print(os.getcwd())
print(os.path.exists("train.csv"))
print(os.path.exists("data/train.csv"))

d:\datascienece_journey\AI-SQL-ASSISTANT
False
True

In [4]:
import os

print(os.path.getsize("data/train.csv"))

2129689

In [5]:
with open("data/train.csv", "r", encoding="utf-8") as f:
    print(f.read(500))

Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,Sout

In [6]:
import pandas as pd

df = pd.read_csv("data/train.csv")

print(df.head())
print(df.shape)

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
(9800, 18)

In [7]:
import sqlite3

conn = sqlite3.connect("database.db")

df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Database created successfully!")

Database created successfully!

In [8]:
query = """
SELECT *
FROM sales
LIMIT 5
"""

result = pd.read_sql(query, conn)

result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [9]:
query = """
SELECT Category,
ROUND(SUM(Sales),2) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology    827455.87
1        Furniture    728658.58
2  Office Supplies    705422.33

In [10]:
query = """
SELECT [Customer Name],
ROUND(SUM(Sales),2) AS Revenue
FROM sales
GROUP BY [Customer Name]
ORDER BY Revenue DESC
LIMIT 10
"""

pd.read_sql(query, conn)

        Customer Name   Revenue
0         Sean Miller  25043.05
1        Tamara Chand  19052.22
2        Raymond Buch  15117.34
3        Tom Ashbrook  14595.62
4       Adrian Barton  14473.57
5        Ken Lonsdale  14175.23
6        Sanjit Chand  14142.33
7        Hunter Lopez  12873.30
8        Sanjit Engle  12209.44
9  Christopher Conant  12129.07

In [11]:
query = """
SELECT Region,
ROUND(SUM(Sales),2) AS Revenue
FROM sales
GROUP BY Region
ORDER BY Revenue DESC
"""

pd.read_sql(query, conn)

    Region    Revenue
0     West  710219.68
1     East  669518.73
2  Central  492646.91
3    South  389151.46

In [13]:
import sys

print(sys.executable)

c:\Users\Vanshika\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [16]:
import sys
print(sys.version)
print(sys.executable)

3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
c:\Users\Vanshika\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [17]:
import google.generativeai as genai

print("Gemini installed successfully!")

Gemini installed successfully!

c:\Users\Vanshika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Vanshika\AppData\Local\Temp\ipykernel_10220\2676244363.py:1: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

In [18]:
import sys

print(sys.executable)

c:\Users\Vanshika\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [20]:
import google.generativeai as genai

genai.configure(api_key=API_KEY)

for model in genai.list_models():
    print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.5-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview

In [21]:
import google.generativeai as genai

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content(
    "What is SQL?"
)

print(response.text)

**SQL** stands for **Structured Query Language**.

It is a specialized programming language used for **managing and querying data in relational databases**. Think of it as the universal language you use to "talk" to a database.

Here's a breakdown of what that means:

1.  **Relational Databases:**
    *   Data is organized into one or more **tables** (also called relations).
    *   Each table consists of **rows** (records) and **columns** (fields).
    *   Tables can be "related" to each other based on common columns, allowing for complex data structures.
    *   Examples of Relational Database Management Systems (RDBMS) that use SQL include MySQL, PostgreSQL, Oracle, SQL Server, SQLite, and many more.

2.  **Structured:**
    *   SQL has a defined syntax and structure that makes it consistent and easy to read.
    *   It's not a general-purpose programming language like Python or Java; its commands are specifically designed for database operations.

3.  **Query Language:**
    *   The primary purpose of SQL is to ask questions (queries) of the database to retrieve specific information.
    *   It also allows you to define, manipulate, and control the data and structure within the database.

---

### What Can You Do with SQL?

SQL commands are generally categorized into a few main types:

1.  **Data Query Language (DQL):**
    *   **`SELECT`**: Retrieves data from one or more tables. This is the most frequently used command.
        *   **Example:** `SELECT name, email FROM Users WHERE age > 30;`

2.  **Data Manipulation Language (DML):**
    *   **`INSERT`**: Adds new rows of data into a table.
        *   **Example:** `INSERT INTO Products (product_name, price) VALUES ('Laptop', 1200.00);`
    *   **`UPDATE`**: Modifies existing data in a table.
        *   **Example:** `UPDATE Users SET email = 'new.email@example.com' WHERE user_id = 123;`
    *   **`DELETE`**: Removes rows of data from a table.
        *   **Example:** `DELETE FROM Orders WHERE order_date < '2023-01-01';`

3.  **Data Definition Language (DDL):**
    *   **`CREATE`**: Creates new database objects (like tables, databases, views, indexes).
        *   **Example:**
            ```sql
            CREATE TABLE Customers (
                customer_id INT PRIMARY KEY,
                first_name VARCHAR(50),
                last_name VARCHAR(50),
                email VARCHAR(100) UNIQUE
            );
            ```
    *   **`ALTER`**: Modifies the structure of existing database objects (e.g., adding or dropping columns).
        *   **Example:** `ALTER TABLE Customers ADD COLUMN phone_number VARCHAR(15);`
    *   **`DROP`**: Deletes entire database objects.
        *   **Example:** `DROP TABLE Customers;`

4.  **Data Control Language (DCL):**
    *   **`GRANT`**: Gives users specific permissions or privileges on database objects.
    *   **`REVOKE`**: Removes previously granted permissions.

---

### Why is SQL So Important?

*   **Ubiquitous:** It's the standard for virtually all relational databases, making it a critical skill for anyone working with data.
*   **Powerful:** It allows you to retrieve, analyze, and manage vast amounts of data efficiently.
*   **Declarative:** You tell the database *what* you want to achieve, not *how* to achieve it, and the database engine figures out the most efficient way to execute your request.
*   **Foundation for Applications:** Almost every web application, mobile app, and enterprise software that stores structured data uses SQL behind the scenes to interact with its database.

In essence, SQL is the essential tool for anyone who needs to store, organize, or extract information from structured datasets.

In [23]:
schema = """
Table Name: sales

Columns:
Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country
City
State
Postal Code
Region
Product ID
Category
Sub-Category
Product Name
Sales
"""

In [24]:
def generate_sql(question):

    prompt = f"""
You are a SQL expert.

Database Schema:

{schema}

Convert the user's question into SQLite SQL.

Rules:
1. Return ONLY SQL.
2. Do not explain.
3. Use SQLite syntax.

Question:
{question}
"""

    response = model.generate_content(prompt)

    return response.text

In [25]:
question = "Show top 5 customers by sales"

sql_query = generate_sql(question)

print(sql_query)

```sqlite
SELECT "Customer Name", SUM(Sales) AS TotalSales
FROM sales
GROUP BY "Customer Name"
ORDER BY TotalSales DESC
LIMIT 5;
```

In [28]:
sql_query = generate_sql(
    "Show top 5 customers by sales"
)

print(sql_query)

```sqlite
SELECT
  "Customer Name",
  SUM(Sales) AS TotalSales
FROM sales
GROUP BY
  "Customer Name"
ORDER BY
  TotalSales DESC
LIMIT 5;
```

In [30]:
def ask_database(question):

    sql_query = generate_sql(question)

    print("Generated SQL:")
    print(sql_query)

    result = pd.read_sql(sql_query, conn)

    return result

In [32]:
ask_database(
    "Show top 10 customers by revenue"
)

Generated SQL:
```sqlite
SELECT
  "Customer Name",
  SUM(Sales) AS TotalRevenue
FROM sales
GROUP BY
  "Customer Name"
ORDER BY
  TotalRevenue DESC
LIMIT 10;
```

DatabaseError: Execution failed on sql '```sqlite
SELECT
  "Customer Name",
  SUM(Sales) AS TotalRevenue
FROM sales
GROUP BY
  "Customer Name"
ORDER BY
  TotalRevenue DESC
LIMIT 10;
```': near "```sqlite
SELECT
  "Customer Name",
  SUM(Sales) AS TotalRevenue
FROM sales
GROUP BY
  "Customer Name"
ORDER BY
  TotalRevenue DESC
LIMIT 10;
```": syntax error

In [33]:
ask_database(
    "Which category generated the highest sales?"
)

Generated SQL:
```sqlite
SELECT Category
FROM sales
GROUP BY Category
ORDER BY SUM(Sales) DESC
LIMIT 1;
```

DatabaseError: Execution failed on sql '```sqlite
SELECT Category
FROM sales
GROUP BY Category
ORDER BY SUM(Sales) DESC
LIMIT 1;
```': near "```sqlite
SELECT Category
FROM sales
GROUP BY Category
ORDER BY SUM(Sales) DESC
LIMIT 1;
```": syntax error

In [2]:
import re

def clean_sql(sql):

    sql = re.sub(r"```[a-zA-Z]*", "", sql)
    sql = sql.replace("```", "")

    return sql.strip()

In [3]:
import google.generativeai as genai

API_KEY = "YOUR_API_KEY"

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

print("Model Loaded")

Model Loaded

c:\Users\Vanshika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Vanshika\AppData\Local\Temp\ipykernel_16552\704486938.py:1: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

In [4]:
schema = """
Table Name: sales

Columns:
Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country
City
State
Postal Code
Region
Product ID
Category
Sub-Category
Product Name
Sales
"""

In [1]:
import re

def clean_sql(sql):

    sql = re.sub(r"```[a-zA-Z]*", "", sql)
    sql = sql.replace("```", "")

    return sql.strip()

In [3]:
def generate_sql(question):

    prompt = f"""
You are a SQLite expert.

Database Schema:

{schema}

Convert the user's question into SQL.

Return only SQL.
No markdown.
No explanation.

Question:
{question}
"""

    response = model.generate_content(prompt)

    sql = clean_sql(response.text)

    return sql

In [4]:
def generate_sql(question):

    prompt = f"""
You are a SQLite expert.

Database Schema:

{schema}

Convert the user's question into SQL.

Return only SQL.
No markdown.
No explanation.

Question:
{question}
"""

    response = model.generate_content(prompt)

    sql = clean_sql(response.text)

    return sql

In [6]:
import pandas as pd
import sqlite3
import google.generativeai as genai
import re

In [7]:
df = pd.read_csv("data/train.csv")

print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680

In [8]:
conn = sqlite3.connect("database.db")

df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Database Ready")

Database Ready

In [9]:
API_KEY = "YOUR_API_KEY"

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

print("Gemini Ready")

Gemini Ready

In [10]:
schema = f"""
Table Name: sales

Columns:
{', '.join(df.columns)}
"""

print(schema)

Table Name: sales

Columns:
Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales

In [11]:
def clean_sql(sql):

    sql = re.sub(r"```[a-zA-Z]*", "", sql)
    sql = sql.replace("```", "")

    return sql.strip()

In [12]:
def generate_sql(question):

    prompt = f"""
You are an SQLite expert.

Database Schema:

{schema}

Convert the user's question into SQL.

Return ONLY SQL.
No markdown.
No explanation.

Question:
{question}
"""

    response = model.generate_content(prompt)

    return clean_sql(response.text)

In [13]:
def ask_database(question):

    sql_query = generate_sql(question)

    print("Generated SQL:")
    print(sql_query)

    result = pd.read_sql(sql_query, conn)

    return result

In [16]:
queries = [
    "Top 5 customers by sales",
    "Sales by region",
    "Highest selling category",
    "Top 10 products by sales"
]

In [22]:
from google import genai

client = genai.Client(
    api_key="AQ.Ab8RN6JYh3g20pPavza4U0JajZAuJKc4GlzH5095yBup_9W-JQ"
)

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="What is SQL?"
)

print(response.text)

**SQL (pronounced "sequel" or S-Q-L")** stands for **Structured Query Language**.

It is the standard and most widely used **programming language for managing and manipulating relational databases.**

Think of it as the language you use to "talk" to a database to store, retrieve, modify, and organize data.

---

Here's a breakdown of what that means:

1.  **Structured:** SQL works with data organized into tables, which have rows and columns, similar to a spreadsheet. Each table represents a specific entity (e.g., Customers, Products, Orders).
2.  **Query:** A "query" is essentially a request for information from the database. You write SQL queries to ask the database specific questions and get results back.
3.  **Language:** SQL has its own syntax, keywords, and rules, allowing you to write instructions that the database system can understand and execute.

---

**What SQL allows you to do:**

SQL provides commands to perform a wide range of operations on databases, commonly categorized into:

*   **Data Query Language (DQL):**
    *   **`SELECT`**: Retrieve data from one or more tables. (This is the most common operation!)
*   **Data Manipulation Language (DML):**
    *   **`INSERT`**: Add new records (rows) into a table.
    *   **`UPDATE`**: Modify existing records in a table.
    *   **`DELETE`**: Remove records from a table.
*   **Data Definition Language (DDL):**
    *   **`CREATE`**: Build new database objects like tables, views, indexes, or the entire database.
    *   **`ALTER`**: Modify the structure of existing database objects (e.g., add a column to a table).
    *   **`DROP`**: Delete entire database objects (tables, views, databases).
*   **Data Control Language (DCL):**
    *   **`GRANT`**: Give users specific permissions to access or manipulate data.
    *   **`REVOKE`**: Remove user permissions.

---

**Why is SQL important?**

*   **Ubiquitous:** It's the standard for almost all relational database management systems (RDBMS) like MySQL, PostgreSQL, Oracle, SQL Server, SQLite, etc. If you learn SQL, you can work with virtually any of these systems.
*   **Powerful:** It allows complex data retrieval and manipulation with relatively simple commands.
*   **Declarative:** You tell the database *what* you want to achieve, not *how* to achieve it. The database engine figures out the most efficient way to execute your request.
*   **Foundation of Data:** Most web applications, business intelligence tools, and data analysis systems rely heavily on SQL to store and retrieve their data.

---

**A Simple SQL Example:**

Let's say you have a table called `Customers` with columns like `CustomerID`, `FirstName`, `LastName`, and `City`.

To get the first name and last name of all customers living in 'New York', you would write:

```sql
SELECT FirstName, LastName
FROM Customers
WHERE City = 'New York';
```

This simple query demonstrates selecting specific columns (`FirstName`, `LastName`) from a table (`Customers`) based on a condition (`City = 'New York'`).

In [24]:
from google import genai

client = genai.Client(api_key=API_KEY)

def generate_sql(question):

    prompt = f"""
You are a SQLite expert.

Database Schema:

{schema}

Convert the question into SQL.

Return ONLY SQL.
No markdown.
No explanation.

Question:
{question}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return clean_sql(response.text)

In [36]:
result = pd.read_sql(query, conn)

result

   Customer Name  TotalSales
0    Sean Miller   25043.050
1   Tamara Chand   19052.218
2   Raymond Buch   15117.339
3   Tom Ashbrook   14595.620
4  Adrian Barton   14473.571

In [35]:
query = """
SELECT "Customer Name",
SUM(Sales) AS TotalSales
FROM sales
GROUP BY "Customer Name"
ORDER BY TotalSales DESC
LIMIT 5
"""

result = pd.read_sql(query, conn)

result

   Customer Name  TotalSales
0    Sean Miller   25043.050
1   Tamara Chand   19052.218
2   Raymond Buch   15117.339
3   Tom Ashbrook   14595.620
4  Adrian Barton   14473.571

In [37]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("database.db")

query = """
SELECT "Customer Name",
SUM(Sales) AS TotalSales
FROM sales
GROUP BY "Customer Name"
ORDER BY TotalSales DESC
LIMIT 5;
"""

result = pd.read_sql(query, conn)

print(result)

   Customer Name  TotalSales
0    Sean Miller   25043.050
1   Tamara Chand   19052.218
2   Raymond Buch   15117.339
3   Tom Ashbrook   14595.620
4  Adrian Barton   14473.571

In [38]:
def ask_database(question):

    question = question.lower()

    if "top customers" in question:
        query = """
        SELECT "Customer Name",
        SUM(Sales) AS TotalSales
        FROM sales
        GROUP BY "Customer Name"
        ORDER BY TotalSales DESC
        LIMIT 5;
        """

    elif "highest category" in question:
        query = """
        SELECT Category,
        SUM(Sales) AS TotalSales
        FROM sales
        GROUP BY Category
        ORDER BY TotalSales DESC
        LIMIT 1;
        """

    elif "sales by region" in question:
        query = """
        SELECT Region,
        SUM(Sales) AS TotalSales
        FROM sales
        GROUP BY Region
        ORDER BY TotalSales DESC;
        """

    else:
        return "Question not supported yet"

    return pd.read_sql(query, conn)

In [39]:
ask_database("top customers")

   Customer Name  TotalSales
0    Sean Miller   25043.050
1   Tamara Chand   19052.218
2   Raymond Buch   15117.339
3   Tom Ashbrook   14595.620
4  Adrian Barton   14473.571

In [40]:
ask_database("highest category")

     Category  TotalSales
0  Technology  827455.873

In [41]:
ask_database("sales by region")

    Region   TotalSales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

In [42]:
ask_database("highest category")

     Category  TotalSales
0  Technology  827455.873